import os

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RECORDINGS_DIR = os.environ.get("RECORDINGS_DIR", os.path.join(PROJECT_ROOT, "recordings"))

MOTION_THRESHOLD = 5000
MOTION_MAX_DURATION = 60
FLASK_PORT = 5000
FLASK_HOST = "0.0.0.0"
FRAME_WIDTH = 1024
FRAME_HEIGHT = 600
FPS = 20
DISK_MIN_FREE_MB = 500
USB_CHECK_INTERVAL = 30
RECORD_MAX_DAYS = 30
FPS_ACTIVE = 20
FPS_IDLE = 5
PREBUFFER_SECS = 5
